# Motoko dependencies (https://mops.one/)

[dependencies]
base = "https://github.com/dfinity/motoko-base#moc-0.8.5"
sequence = "https://github.com/matthewhammer/motoko-sequence#366c4191d856ed4842267f5ab89d7222ed2d71d0"
